print('hi,there')
print('This quiz is programmed by Harshit Tripathi')
print('copyright 2021 Harshit Tripathi')
print('Lets Start')
print('1. Who was the Indias First Prime Minister? ')
x=input('Your Answer  ')
print('Correct Answer is Pt. Jawaharlal Nehru')
print('2. Who had won the 1983 World Cup?')
x=input('Your Answer  ')
print('Correct Answer is India')
print('3. Who had won the 2015 ICC World Cup?')
x=input('Your Answer  ')
print('Correct Answer is Australia')
print('4. Who was Indias first President?')
x=input('Your Answer  ')
print('Correct Answer is Rajendra Prasad')
print('5. Who had won the first Nobel Prize in asia?')
x=input('Your Answer  ')
print('Correct Answer is Rabindranath Tagore')
print('Quiz Ends..')
print('Thanks for taking this quiz.')
print('Do you have any question?  ')
print('tell us your question. ')
g=input('enter your question  ')
print('Program Ends.....')

